# Generated by Django 3.1.4 on 2021-04-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='users/'),
        ),
    ]
