# Generated by Django 3.1.4 on 2021-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210405_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
