# Generated by Django 3.1.4 on 2021-04-17 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210409_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
